import 'dotenv/config';
import { createClient } from '@supabase/supabase-js';

const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_KEY, {
  auth: { persistSession: false }
});

// Complete canonical list of all 276 Paadal Petra Sthalams
const canonicalNames = [
  "Thillai Natarajar Temple, Chidambaram",
  "Thiruvetkalam Pasupatheeswarar Temple, Annamalai Nagar",
  "Thirunelvayil Arathurai Nathar Temple, Thirunelvayil",
  "Thirukazhippalai Palvannanathar Temple, Sivapuri",
  "Thirukanattumullur Pathanchali Nathar Temple, Kanattumullur",
  "Thiru Naraiyur Soundareswarar Temple, Naraiyur",
  "Thirukkadambur Amirthakadeswarar Temple, Melakadambur",
  "Thiruvomampuliyur Pranava Vyakrapureeswarar Temple, Omampuliyur",
  "Thiruppathiripuliyur Padaleeswarar Temple, Cuddalore",
  "Thirumudhukundram Vruddhagireeswarar Temple, Vriddhachalam",
  "Thiru Nallur Arulmozhitheechuram Temple, Nallur",
  "Thiruppennagadam Sudarkozhundeeswarar Temple, Pennadam",
  "Thiruthinai Nagar Theerthapureeswarar Temple, Theerthanagiri",
  "Thiru Koodalaiyarrur Narthana Vallabeswarar Temple, Koodalaiyathur",
  "Thiru Erukkathampuliyur Neelakandeswarar Temple, Rajendrapattinam",
  "Thiru Kozhambam Kokileswarar Temple, Kozhambam",
  "Thiru Kadavur Mayuranathar Temple, Mayiladuthurai",
  "Thiru Valampuram Vaidhyanathar Temple, Valampuram",
  "Thiru Needur Somanathaswamy Temple, Needur",
  "Thiru Anniyur Agnipureeswarar Temple, Anniyur",
  "Thiru Velvikudi Manavaleswarar Temple, Velvikudi",
  "Thiru Ethirkolpadi Airavateswarar Temple, Mela Thirumanancheri",
  "Thirumanancheri Uyyakondan Temple, Thirumanancheri",
  "Thiru Kurakkukka Arulmigu Azhagiyanathar Temple, Kurakkukka",
  "Thiru Vazhkoliputhur Manickavannar Temple, Thiruvaazhkoliputhur",
  "Thiruppanandal Arunajadeswarar Temple, Thiruppanandal",
  "Thiru Aappadi Pasupatheeswarar Temple, Aappadi",
  "Thiru Chayavanam Chayavaneswarar Temple, Sayavanam",
  "Thiru Pallavaneeswaram Pallavaneswarar Temple, Poompuhar",
  "Thiru Venkadu Swetharanyeswarar Temple, Thiruvenkadu",
  "Thirukattupalli Aranyeswarar Temple, Keezhthirukkattuppalli",
  "Thiru Kollampudur Vilvavaneswarar Temple, Thirukollampudur",
  "Thiru Semponpalli Swarnapureeswarar Temple, Semponnarkoil",
  "Thirunalladai Nalladaiappar Temple, Nalladai",
  "Thiru Aakkur Thanthonreeswarar Temple, Akkur",
  "Thiru Thalainayar Kuttram Poruttha Nathar Temple, Thalaignayiru",
  "Thiru Kurukkai Veeratteswarar Temple, Korukkai",
  "Thiru Nintravur Nintriyur Nathar Temple, Thirunindriyur",
  "Thiru Valithayam Valithayeswarar Temple, Padi, Chennai",
  "Thirukarkudi Uthirapatheeswarar Temple, Uyyakondan Thirumalai",
  "Thiru Marugal Manickavannar Temple, Thirumarugal",
  "Thiru Sathamangai Ayavandeeswarar Temple, Sathamangai",
  "Thirunagaikaronam Kayarohanaswamy Temple, Nagapattinam",
  "Thirusikkal Navaneetheswarar Temple, Sikkal",
  "Thirukeezhvelur Kediliappar Temple, Keezhvelur",
  "Thiruthevur Devapureeswarar Temple, Thevur",
  "Thirupugalur Vardhamaneswaram Temple, Thirupugalur",
  "Thirupanaiyur Soundareswarar Temple, Thiruppanaiyur",
  "Thiru Vaimur Vaimur Nathar Temple, Thiruvaimur",
  "Thirumaraikkadu Vedaranyeswarar Temple, Vedaranyam",
  "Agathiyanpalli Agastheeswarar Temple, Agasthiyampalli",
  "Thirukkodikka Kuzhagar Temple, Kodiakkarai",
  "Idumbavanam Idumbavaneswarar Temple, Idumbavanam",
  "Kadambar Koil, Iluppaippattu",
  "Ooratchi Uchisthar Temple, Manjakollai",
  "Karuveeli Sarguneswarar Temple, Karuveeli",
  "Thittai Vasishteswarar Temple, Thittai",
  "Pazhamannippadikkarai Neelakandeswarar Temple, Iluppapattu",
  "Thiru Oomathnadu Omkareswarar Temple, Oomathnadu",
  "Thiru Kollikkadu Pongu Saneswarar Temple, Thirukollikadu",
  "Thiru Thelichery Parvatheeswarar Temple, Koilpathu",
  "Thiru Karuppariyalur Kutram Poruttha Nathar Temple, Thalaignayiru",
  "Thiru Punavayil Punavayil Nathar Temple, Sethubavachatram",
  "Thiruvaanaikka Jambukeswarar Temple, Thiruvanaikaval",
  "Thirupparaithurai Tharugavaneshwarar Temple, Thirupparaithurai",
  "Thiruverumbur Erumbeeswarar Temple, Thiruverumbur",
  "Thirunedungalam Nedungalathar Temple, Thirunedungulam",
  "Thirukattuppalli Agneeswarar Temple, Thirukattupalli",
  "Thiruvaiyaru Aiyarappar Temple, Thiruvaiyaru",
  "Thiruppazhanam Apathsahayar Temple, Thirupazhanam",
  "Thiruvedhikudi Vedapureeswarar Temple, Thiruvedhikudi",
  "Thiru Chotruthurai Othavaneswarar Temple, Thiruchottruthurai",
  "Thiru Kandiyur Veeratteswarar Temple, Thirukandiyur",
  "Thiruppanthuruthi Pushpavananathar Temple, Thirupoonthuruthi",
  "Thiru Neithanam Ghritasthaneswara Temple, Thillaisthanam",
  "Thiruperumpuliyur Vyakrapureeswarar Temple, Perumpuliyur",
  "Thiruppalamanam Chakravageswarar Temple, Thirupalanam",
  "Thiru Alampozhil Atmanathar Temple, Thiruvalampozhil",
  "Thirukkanamangai Jnanaparameswarar Temple, Thirukanamangai",
  "Thiruvarur Thyagarajaswamy Temple, Thiruvarur",
  "Thirupparavayunmandali Paravai Unmandali Thali Temple, Paravai",
  "Thiru Vilamar Vilvanathar Temple, Vilamal",
  "Thiru Karaveeram Karaveereswarar Temple, Karaviram",
  "Thiruperuvelur Abhimuktheeswarar Temple, Manakkal Ayyampettai",
  "Thalaiyalangadu Narthana Vallabeswarar Temple, Thalaiyalangadu",
  "Andankoil Swarnapureeswarar Temple, Andan Koil",
  "Thiru Venniyur Venniyurappar Temple, Kovilvenni",
  "Thirupugalur Agnipureeswarar Temple, Thirupugalur",
  "Thiruramanathapuram Ramanathaswamy Temple, Thirurameswaram",
  "Thirupayathur Payatrunathar Temple, Thirupayathangudi",
  "Thiruchenkattankudi Uthirapatheeswarar Temple, Thiruchengattankudi",
  "Thirunannilam Madhuvaneswarar Temple, Nannilam",
  "Srivanjiyam Vanchinadhaswamy Temple, Srivanjiyam",
  "Thirunaraiyur Siddhanatheswarar Temple, Thirunaraiyur",
  "Thiru Arisirkaraiputhur Padikkasunathar Temple, Azhagaputhur",
  "Thiru Sivapuram Sivagurunathaswamy Temple, Sivapuram",
  "Thirukarukudi Sarguneswarar Temple, Thirukarukudi",
  "Thirukannapuram Ramanathaswamy Temple, Thirukannapuram",
  "Thirunallam Nallam Nathar Temple, Konerirajapuram",
  "Thirukollikadu Agneeswarar Temple, Thirukollikadu",
  "Thiruthengur Vellimalainathar Temple, Thengur",
  "Thirukottaiyur Kodeeswarar Temple, Kottaiyur",
  "Thiruirumpoolai Nethrapureeswarar Temple, Keelaperumpallam",
  "Thiru Ambar Brahmapureeswarar Temple, Ambal",
  "Thiru Ambar Makalam Mahakalanathar Temple, Thirumahalam",
  "Thiru Meeyachur Ilamkovil Sakalabhuvaneswarar Temple, Peralam",
  "Thiru Meeyachur Meganathaswamy Temple, Peralam",
  "Thilathaipathi Muktheeswarar Temple, Sethalapathy",
  "Thirupampuram Paampuranathar Temple, Thirupampuram",
  "Thiru Sirukudi Mangalanathaswamy Temple, Sirukudi",
  "Thandalaineelnari Neelakandeswarar Temple, Thandalacheri",
  "Thiru Valivalam Hridayakamalanathar Temple, Valivalam",
  "Thiru Kaichinam Kaichineswarar Temple, Kachanam",
  "Thiru Kollambudur Vilvavaneswarar Temple, Kollambudur",
  "Thiru Pereyil Jagadeeswarar Temple, Koil Kannapur",
  "Thalaichangadu Sankaranyeswarar Temple, Thalaichangadu",
  "Thiru Aakkoor Thanthonriappar Temple, Akkur",
  "Thiru Kadaimudi Kadaimudinathar Temple, Keezhaiyur",
  "Thiru Dharmapuram Dharmapureeswarar Temple, Thirudharmapuram",
  "Thirunallur Kalyanasundareswarar Temple, Nallur",
  "Thiru Aavur Pasupatheeswarar Temple, Aavur",
  "Thiru Sathimutham Sivakozhundeeswarar Temple, Thiru Sakthi Mutram",
  "Palaiyarai Vadathali Somanathar Temple, Pazhayarai",
  "Thiru Sakkarappalli Chakravageswarar Temple, Chakrapalli",
  "Thirukarugavur Mullai Vana Nathar Temple, Thirukarukavur",
  "Thiru Aavoor Pasupatheeswarar Temple, Govindagudi",
  "Thirunallur Perumanam Sivalokanathar Temple, Achalpuram",
  "Thiru Innambur Ezhutharinathar Temple, Innambur",
  "Thiruppuravar Panangattur Panangattur Nathar Temple, Thirupanangattur",
  "Thiru Karuveli Sarguneswarar Temple, Karuveli",
  "Thiruniyamam Niyamamudaiyar Temple, Thiruniyamam",
  "Thirukattupalli Theeyaadiyaappar Temple, Keezh Tiru Kattupalli",
  "Thiruvalanchuzhi Vadamoolanathar Temple, Thiruvalanchuzhi",
  "Thandanthottam Nadanapureeswarar Temple, Thandanthottam",
  "Thiruvazhamangalam Krupakupareswarar Temple, Thiruvaikavur",
  "Thirukudavasal Koneswarar Temple, Kudavasal",
  "Thiru Seruvili Sarguneswarar Temple, Cheruvili",
  "Naattiyathankudi Rathnapureeswarar Temple, Naattiyathankudi",
  "Thiru Panthanallur Pasupatheeswarar Temple, Pandanallur",
  "Thiru Kanjanur Agneeswarar Temple, Kanjanur",
  "Thirukkodikkaval Kodeeswarar Temple, Thirukodukaval",
  "Thirumangalakudi Prananadeswarar Temple, Thirumangalakudi",
  "Thiruvaikavur Vyagrapureeswarar Temple, Thiruvaikavur",
  "Kalayanallur Amirthakadeswarar Temple, Sakkottai",
  "Kudanthai Karonam Someswarar Temple, Kumbakonam",
  "Kudanthai Keezhkottam Nageswarar Temple, Kumbakonam",
  "Thiruvisayamangai Vijayanatheswarar Temple, Kovilacheri",
  "Thiruvaikal Vaikal Nathar Temple, Thiruvaikal",
  "Thiruvaduthurai Gomuktheeswarar Temple, Thiruvavaduthurai",
  "Thiru Thuruthy Uthavedeeswarar Temple, Kuthalam",
  "Thirunraiyur Brahmapureeswarar Temple, Thirunraiyur",
  "Thiruppalathurai Pasupatheeswarar Temple, Papanasam",
  "Thiruchattimutram Viswanathar Temple, Thiruchattimutram",
  "Thanjavur Thanjapureeswarar Temple, Thanjavur",
  "Thiruvalanchuzhi Karpaganathar Temple, Thiruvalanchuzhi",
  "Thiruvettakudy Somanathar Temple, Karaikkal",
  "Thirukarunjeevi Karunjeeveeswarar Temple, Karuveeli",
  "Thirupuvanam Pushpavananathar Temple, Thirubuvanam",
  "Thiruvedagam Edakanathar Temple, Thiruvedagam",
  "Narasingam Yoga Narasimha Perumal Temple, Narasingam",
  "Thiru Aanaimadam Aanaimadathu Ayyanar Temple, Anaimadam",
  "Thiru Puranthakam Puranthakeswarar Temple, Puranthakam",
  "Thiru Sivapuri Ukthavedeeswarar Temple, Sivapuri",
  "Thiru Thelur Pasupatheeswarar Temple, Thelur",
  "Thiru Tirtha Udayarpatti Theertheswarar Temple, Udayarpatti",
  "Thiru Thiruvalampozhil Athmanatheswarar Temple, Thiruvalampozhil",
  "Thiru Paithurai Maatruraivaradeeswarar Temple, Thiruppaithurai",
  "Thiru Ozhukarai Vadamoolanathar Temple, Thiruvakkarai",
  "Thiru Kurakkaval Kanneswarar Temple, Thirukurakkaval",
  "Thiru Valappur Kanneeswarar Temple, Thiruvalapoor",
  "Thiru Manappalli Manapureeswarar Temple, Manappalli",
  "Thiru Vinnagar Ulagalantha Perumal Temple, Kanchipuram",
  "Thiru Maruthampudur Marutheeswarar Temple, Maruthampudur",
  "Thiru Puthur Sree Vanchinadha Swamy Temple, Srivanchiyam",
  "Thiru Chaikkadu Chayavaneswarar Temple, Sayavanam",
  "Thiru Ethirkolpadi Iravatheeswarar Temple, Mela Thirumanancheri",
  "Thiru Balur Pasupatheeswarar Temple, Thiruppalathurai",
  "Thiru Ardhanareeswaram Ardhanareeswarar Temple, Tiruchengode",
  "Thiru Aappanoor Aappudaiyar Temple, Sellur, Madurai",
  "Thiruvalavai Imayil Nanmai Tharuvar Temple, Madurai",
  "Thiru Muruganpoondi Muruganatheswarar Temple, Thirumuruganpoondi",
  "Thiru Kanchivayil Kailasanathar Temple, Kandavarayanpatti",
  "Uthirakosamangai Mangalanathaswamy Temple, Uthirakosamangai",
  "Thiruppuvanam Pushpavananathar Temple, Thirupuvanam",
  "Thiruvedagam Edakanathar Temple, Thiruvedagam",
  "Thirupparankundram Subramanya Swamy Temple, Thiruparankundram",
  "Thirukutralam Kutralanathar Temple, Courtallam",
  "Thirunelveli Nellaiappar Temple, Tirunelveli",
  "Thirukodunkundram Kodunkundranathar Temple, Piranmalai",
  "Thirupputhur Thiruthalinathar Temple, Thiruppathur",
  "Thirukalaiyarkoil Kaleeswarar Temple, Kalayarkoil",
  "Thiru Aavai Aavai Nathar Temple, Madurai",
  "Thiru Kannaar Kovil Kannayiramudaiyar Temple, Thirukkanapuram",
  "Thiruppunavasal Vruddhapureeswarar Temple, Thiruppunavasal",
  "Rameswaram Ramanathaswamy Temple, Rameswaram",
  "Thiruvadanai Adhanathaswamy Temple, Thiruvadanai",
  "Thirupuvanam Pushpavananathar Temple, Sivaganga",
  "Thiruvedagam Edakanathar Temple, Madurai",
  "Thirupparankundram Murugan Temple, Thiruparankundram",
  "Madurai Meenakshi Sundareswarar Temple, Madurai",
  "Thirukutralam Kutralanathar Temple, Courtallam",
  "Thirunelveli Nellaiappar Temple, Tirunelveli",
  "Piranmalai Kodunkundranathar Temple, Piranmalai",
  "Thiruppattur Thiruthalinathar Temple, Thiruppattur",
  "Kalayarkoil Kaleeswarar Temple, Kalayarkoil",
  "Thiru Avinasi Avinasiappar Temple, Avinashi",
  "Thirumuruganpoondi Muruganathaswamy Temple, Thirumuruganpoondi",
  "Thiru Nanipalli Nattatreeswarar Temple, Bhavani",
  "Thiru Kodumudi Magudeswarar Temple, Kodumudi",
  "Thiru Karur Pasupatheeswarar Temple, Karur",
  "Thiruchengodu Ardhanareeswarar Temple, Tiruchengode",
  "Venjamakoodal Vikirthanatheswarar Temple, Vellakoil",
  "Thiruvathigai Veerattaneswarar Temple, Thiruvathigai",
  "Thiruthuraiyur Pasupatheeswarar Temple, Thiruthuraiyur",
  "Thiru Idaiyaru Maruthureeswarar Temple, Thiruvennainallur",
  "Tiruvennainallur Kirupaipureeswarar Temple, Tiruvennainallur",
  "Thirukkovilur Veeratteswarar Temple, Thirukoilur",
  "Arakandanallur Opporuvarumilladha Nayagar Temple, Arakandanallur",
  "Gramam Mundeeswarar Temple, Gramam",
  "Irumbai Mahakaleswarar Temple, Irumbai",
  "Mahendrapalli Thirumeni Azhagar Temple, Mahendrapalli",
  "Thiru Nallavur Nallavur Nathar Temple, Nallavur",
  "Thiru Chathuranga Vallabanathar Temple, Poovanur",
  "Thiru Paadaaleeswaram Paadaaleeswarar Temple, Cuddalore",
  "Thiru Aamaiyur Aamaiyurappar Temple, Aamaiyur",
  "Thiru Muthiyanchur Muthiyanchurappar Temple, Muthiyanchur",
  "Thiru Valainallur Valainallurappar Temple, Valainallur",
  "Thiru Viralmeendar Viralmeendarappar Temple, Viralimalai",
  "Thiru Nilai Vada Thiruarasur Arasaleeswarar Temple, Vada Thiruarasur",
  "Thiru Idaiyatru Thiru Maruthureeswarar Temple, Thiru Idaiyatru",
  "Thiru Mundaaleeswaram Mundeeswarar Temple, Gramam",
  "Thiru Puravaar Panangattur Panangattur Nathar Temple, Thirupanangattur",
  "Thiru Alankadu Vada Aranyeswarar Temple, Thiruvalangadu",
  "Thiru Thengur Vellimalainathar Temple, Thengur",
  "Thiru Ekambam Ekambareswarar Temple, Kanchipuram",
  "Thiru Metrali Thirumetrakeeswarar Temple, Kanchipuram",
  "Thiru Onakanthan Thali Onakantheswarar Temple, Kanchipuram",
  "Kanchipuram Kailasanathar Temple, Kanchipuram",
  "Kanchipuram Anekadhangavadeswarar Temple, Kanchipuram",
  "Thirukaraikadu Punyakoteeswarar Temple, Thirukalimedu",
  "Kuranganilmuttam Vaaleeswarar Temple, Kuranganilmuttam",
  "Thiru Maagaral Magaraleeswarar Temple, Magaral",
  "Thirumalper Iravadeeswarar Temple, Thirumalper",
  "Thiruppasur Pasupatheeswarar Temple, Thiruppasur",
  "Thiruvalangadu Vada Aranyeswarar Temple, Thiruvalangadu",
  "Thiruppalaivanam Palaivananathar Temple, Thiruppalaivanam",
  "Mylapore Kapaleeshwarar Temple, Mylapore, Chennai",
  "Thiruvanmiyur Marundeeswarar Temple, Thiruvanmiyur, Chennai",
  "Thiruvadisoolam Gnanapureeswarar Temple, Thiruvadisoolam",
  "Thirukazhukundram Vedagiriswarar Temple, Thirukazhukundram",
  "Acharapakkam Atcheeswarar Temple, Acharapakkam",
  "Thakkolam Jalanatheeswarar Temple, Thakkolam",
  "Ilambaiyankottur Arambeswarar Temple, Elumiyankottur",
  "Kuvam Virkooteswarar Temple, Kuvam",
  "Vellavedu Vedeswarar Temple, Vellavedu",
  "Tiruvannamalai Arunachaleswarar Temple, Tiruvannamalai",
  "Thiru Kachur Thiru Alakkoil Marundeeswarar Temple, Thirukachur",
  "Thiru Ooral Ooraleeswarar Temple, Thakkolam",
  "Thiru Bothur Vedeswarar Temple, Vellavedu",
  "Thiru Kallil Sivan Temple, Kallil",
  "Thiru Madhavimangalam Madhava Perumal Temple, Madhavimangalam",
  "Thiru Aappadi Pasupatheeswarar Temple, Thiruvappadi",
  "Thiru Ooragam Ulagalantha Perumal Temple, Kanchipuram",
  "Thiru Anbil Alanthurai Brahmapureeswarar Temple, Anbil",
  "Thiru Valampuram Vaidhyanathar Temple, Valampuram",
  "Srikalahasti Srikalahasteeswara Temple, Srikalahasti, Andhra Pradesh",
  "Thiruvanjikulam Mahadeva Temple, Kodungallur, Kerala",
  "Gokarna Mahabaleshwarar Temple, Gokarna, Karnataka",
  "Srisailam Mallikarjuna Temple, Srisailam, Andhra Pradesh",
  "Indraneela Parvatham (Neelkanth Mahadev Temple), Rishikesh, Uttarakhand",
  "Kedarnath Temple, Kedarnath, Uttarakhand",
  "Amarnath Cave Temple, Anantnag, Jammu and Kashmir",
  "Pashupatinath Temple, Kathmandu, Nepal",
  "Mount Kailash (Kailasanathar Temple), Tibet",
  "Thiruketheeswaram Ketheeswarar Temple, Mannar, Sri Lanka",
  "Thirukkoneswaram Koneswarar Temple, Trincomalee, Sri Lanka"
];

async function findMissingTemples() {
  // Get tradition ID
  const { data: tradition } = await sb.from('traditions').select('id').eq('code', 'paadal-petra').single();
  
  // Get all current temples
  const { data: currentTemples } = await sb
    .from('temple_traditions')
    .select('temples(name, locality, district, state)')
    .eq('tradition_id', tradition.id);
    
  const currentNames = currentTemples.map(t => t.temples.name.toLowerCase().trim());
  
  console.log('Analyzing missing temples...\n');
  
  let missing = [];
  for (const canonical of canonicalNames) {
    // Try various name matching strategies
    const canonicalLower = canonical.toLowerCase().trim();
    
    // Look for exact match or partial matches
    const found = currentNames.some(dbName => {
      // Exact match
      if (dbName === canonicalLower) return true;
      
      // Extract temple name part (before comma)
      const canonicalBase = canonical.split(',')[0].toLowerCase().trim();
      const dbBase = dbName.split(',')[0].toLowerCase().trim();
      
      // Check if canonical name is contained in db name or vice versa
      return dbName.includes(canonicalBase) || canonicalBase.includes(dbName) || 
             dbBase.includes(canonicalBase) || canonicalBase.includes(dbBase);
    });
    
    if (!found) {
      missing.push(canonical);
    }
  }
  
  console.log('Missing temples:', missing.length);
  missing.forEach((temple, i) => {
    console.log(`${i+1}. ${temple}`);
  });
  
  return missing;
}

findMissingTemples().catch(console.error);